<?php

return [
    'PAYTM_ENVIRONMENT' => 'local',
    #'PAYTM_MERCHANT_ID' => 'mQcsIc44516873467454',
    'PAYTM_MERCHANT_ID' => 'BARCOU52881362955913',
    #'PAYTM_MERCHANT_KEY' => '04bqnluwDZ5AF%PU',
    'PAYTM_MERCHANT_KEY' => 'fCe9&Jt%ip#ykNO2',
    'PAYTM_MERCHANT_WEBSITE' => 'WEBSTAGING',
    'PAYTM_CHANNEL' => 'YOUR_MERCHANT_CHANNEL',
    'PAYTM_INDUSTRY_TYPE' => 'Retail',
    'PAYTM_CHANNEL_WEBSITE' => 'WEB',
    'PAYTM_CHANNEL_APP' => 'WAP',
];