<?php

return [
    'PAYTM_ENVIRONMENT' => 'production',
    #'PAYTM_MERCHANT_ID' => 'mQcsIc44516873467454',
    'PAYTM_MERCHANT_ID' => 'BARCOU48391458223205',
    #'PAYTM_MERCHANT_KEY' => '04bqnluwDZ5AF%PU',
    'PAYTM_MERCHANT_KEY' => 'NW87Bq_UZ6_2BUR1',
    'PAYTM_MERCHANT_WEBSITE' => 'WEBSTAGING',
    'PAYTM_CHANNEL' => 'YOUR_MERCHANT_CHANNEL',
    'PAYTM_INDUSTRY_TYPE' => 'Retail',
    'PAYTM_CHANNEL_WEBSITE' => 'WEB',
    'PAYTM_CHANNEL_APP' => 'WAP',
];
