<?php

return [
    'PAYTM_ENVIRONMENT' => 'local',
    'PAYTM_MERCHANT_ID' => 'mQcsIc44516873467454',
    'PAYTM_MERCHANT_KEY' => '04bqnluwDZ5AF',
    'PAYTM_MERCHANT_WEBSITE' => 'YOUR_MERCHANT_WEBSITE',
    'PAYTM_CHANNEL' => 'YOUR_MERCHANT_CHANNEL',
    'PAYTM_INDUSTRY_TYPE' => 'Retail'
];